services:
  training_env:
    image: kaldi-training-env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NAME: "Preben Vangberg"
        AFFIL: "Bangor University"
        EMAIL: "prv21fgt@bangor.ac.uk"
        ADDRESS: "Bangor, UK"
        USERNAME: prv21fgt
        USER_UID: 1004
        USER_GID: 1005
    volumes:
      - .:/workspaces/vosk
    stdin_open: true
    tty: true
volumes:
  .:
